name: AI Translator
on:
  push:
    paths:
      - 'AI Translator/**'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  translate:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    environment: myRG
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install axios cheerio glob
        
      # - name: Install Azure CLI
      #   run: |
      #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # - name: add entry in hosts
      #   run: |
      #     sudo echo "172.19.1.4 aitranslatorpn7qikovfvu32.cognitiveservices.azure.com" >> /etc/hosts
      #     sudo cat /etc/hosts

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      
      - name: Get OAuth Token for Translator
        id: get-token
        run: |
          TOKEN=$(az account get-access-token --resource https://cognitiveservices.azure.com/ --query accessToken --output tsv)
          echo "TOKEN=$TOKEN" >> $GITHUB_OUTPUT
      
      - name: Call the API
        run: |
          curl -v -X POST "https://aitranslatorpn7qikovfvu32.cognitiveservices.azure.com/translate?api-version=3.0&to=fr" \
          -H "Authorization: Bearer ${{ steps.get-token.outputs.TOKEN }}" \
          -H "Content-Type: application/json" \
          -H "Ocp-Apim-Subscription-Region: eastus" \
          -H "Ocp-Apim-ResourceId: /subscriptions/2cab150b-4433-4b0e-95a8-fabb980b3485/resourceGroups/myRG/providers/Microsoft.CognitiveServices/accounts/aitranslatorpn7qikovfvu32" \
          --data-raw '[{"text":"Hello, world!"}]'


      # - name: Run Translation Script
      #   run: node aitranslate.js
      #   env:
      #     AZURE_TRANSLATOR_TOKEN: ${{ steps.get-token.outputs.TOKEN }}
      #     AZURE_TRANSLATOR_ENDPOINT: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
      
      # - name: Verify translated files
      #   run: |
      #     echo "Translated files:"
      #     run: node verify.js
